name: terraform-plan (PR)

on:
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform-plan.yml"

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: dev # <-- uses Environment 'dev' variables
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform init (inject backend config)
        working-directory: infra/terraform/iam-oidc
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TFSTATE_BUCKET }}" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.TF_LOCK_TABLE }}" \
            -backend-config="kms_key_id=${{ vars.TFSTATE_KMS_ARN }}" \
            -backend-config="key=iam-oidc/terraform.tfstate"

      - name: Terraform fmt/validate
        working-directory: infra/terraform/iam-oidc
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform plan (no apply)
        working-directory: infra/terraform/iam-oidc
        run: terraform plan -lock-timeout=5m -input=false
